### ISSUE TITLE
Include sourceMap

### ISSUE THREAD

**Issue by edwinm** [blakewilson/tsconfig.guide#2]
Many developers don't know about sourceMap and when they look at the code in de browser inspector, they see generated JavaScript instead of the TypeScript they wrote, which can be cumbersome.

Please add sourceMap support.

```
...
    "sourceMap": true,
...
```

**Comment by blakewilson** [comment]
@edwinm Thanks for opening an issue!

This is currently added to the `tsconfig.json` output if you select "Are you building a library or something that will be used by others?". For libraries, it makes sense to include source maps. For private projects in which the source code is not open, I think it's best for the user to add this manually for now.
