### ISSUE TITLE
Mark in color the last change

### ISSUE THREAD

**Issue by GiladShoham** [blakewilson/tsconfig.guide#3]
The tsconfig is changed everytime you check/uncheck something
but it's hard to notice what was changed.
I recommend to highlight with color / background color / +/- sign the last change made

**Comment by blakewilson** [comment]
Hi @GiladShoham, thanks for opening an issue!

I totally agree, and have heard this from others too. I'm working on something now. I'll respond here when it's released.

**Comment by blakewilson** [comment]
Hey @GiladShoham, just added this. It's live now on https://tsconfig.guide. Thanks for the feature request!

**Comment by GiladShoham** [comment]
looks great! thanks :)
